services:
  # Nginx Web Server
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  # PHP-FPM Application
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "9000"

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-nginx

volumes:
  mysqldata:
