services:
  # Nginx Web Server
  web:
    image: nginx:1.27.3
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  # PHP-FPM Application
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: php:8.2.27-fpm-alpine-acetopia
    volumes:
      - ./app:/app
    expose:
      - "9000"

  # MySQL Database
  db:
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-nginx

volumes:
  mysqldata:
